# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class MyLineEdit(QtWidgets.QLineEdit):

    def __init__(self, parent):
        super(MyLineEdit, self).__init__(parent)
        #super(CustomQLineEidt, self).__init__()

    def mousePressEvent(self, e):
        self.mouseseleted()

    def mouseseleted(self):
        self.clear()
        self.setStyleSheet("color: rgb(0,0,0);\n"
"border: 1.3px solid rgb(150,150,150);\n"
"font-size: 14px;")


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(504, 500)
        Form.setWindowIcon(QtGui.QIcon("assets/logo.jpg"))
        self.frame_29 = QtWidgets.QFrame(Form)
        self.frame_29.setGeometry(QtCore.QRect(0, 0, 500, 500))
        self.frame_29.setMinimumSize(QtCore.QSize(500, 500))
        self.frame_29.setMaximumSize(QtCore.QSize(500, 500))
        self.frame_29.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_29.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_40.setSpacing(15)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.label_125 = QtWidgets.QLabel(self.frame_29)
        self.label_125.setStyleSheet("font-size: 40px;")
        self.label_125.setObjectName("label_125")
        self.verticalLayout_40.addWidget(self.label_125, 0, QtCore.Qt.AlignHCenter)
        self.label_126 = QtWidgets.QLabel(self.frame_29)
        self.label_126.setMinimumSize(QtCore.QSize(0, 50))
        self.label_126.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_126.setStyleSheet("font-size: 16px;\n"
"color: #353946;")
        self.label_126.setObjectName("label_126")
        self.verticalLayout_40.addWidget(self.label_126, 0, QtCore.Qt.AlignHCenter)
        self.tel_8 = MyLineEdit(self.frame_29)
        self.tel_8.setMinimumSize(QtCore.QSize(300, 25))
        self.tel_8.setMaximumSize(QtCore.QSize(300, 28))
        self.tel_8.setStyleSheet("color: rgb(140, 140, 140);\n"
"border: 1.3px solid rgb(206, 206, 206);\n"
"font-size: 14px;")
        self.tel_8.setAlignment(QtCore.Qt.AlignCenter)
        self.tel_8.setObjectName("tel_8")
        self.verticalLayout_40.addWidget(self.tel_8, 0, QtCore.Qt.AlignHCenter)
        self.mdp_4 = MyLineEdit(self.frame_29)
        self.mdp_4.setMinimumSize(QtCore.QSize(300, 25))
        self.mdp_4.setMaximumSize(QtCore.QSize(300, 28))
        self.mdp_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.mdp_4.setStyleSheet("color: rgb(140, 140, 140);\n"
"border: 1.3px solid rgb(206, 206, 206);\n"
"font-size: 14px;")
        self.mdp_4.setAlignment(QtCore.Qt.AlignCenter)
        self.mdp_4.setObjectName("mdp_4")
        self.verticalLayout_40.addWidget(self.mdp_4, 0, QtCore.Qt.AlignHCenter)
        self.connecter_4 = QtWidgets.QPushButton(self.frame_29)
        self.connecter_4.setMinimumSize(QtCore.QSize(200, 35))
        self.connecter_4.setMaximumSize(QtCore.QSize(200, 35))
        self.connecter_4.setStyleSheet("font-size: 18px;\n"
"border: none;\n"
"background-color: rgb(57, 195, 221);\n"
"padding: 10px 0px 10px 0px;\n"
"color: white;\n"
"")
        self.connecter_4.setObjectName("connecter_4")
        self.verticalLayout_40.addWidget(self.connecter_4, 0, QtCore.Qt.AlignHCenter)
        self.label_127 = QtWidgets.QLabel(self.frame_29)
        self.label_127.setMinimumSize(QtCore.QSize(0, 40))
        self.label_127.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_127.setFont(font)
        self.label_127.setStyleSheet("font-size: 13px;\n"
"color: rgb(100, 100, 100);")
        self.label_127.setObjectName("label_127")
        self.verticalLayout_40.addWidget(self.label_127, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(25, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_40.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Port-Gest"))
        self.label_125.setText(_translate("Form", "Bienvenu!"))
        self.label_126.setText(_translate("Form", "Veuillez vous-connecter à votre compte"))
        self.tel_8.setText(_translate("Form", "identifiant "))
        self.mdp_4.setText(_translate("Form", "mot de passe"))
        self.connecter_4.setText(_translate("Form", "se connecter"))
        self.label_127.setText(_translate("Form", "mot de passe oublié ?"))


